version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.6.3-node
    environment:
      PIPENV_VENV_IN_PROJECT: true
commands:
  setup:
    steps:
      - run:
          name: Check python version
          command: |
            python -V
            pip -V
      - run:
          name: Install pipenv
          command: |
            sudo pip install pipenv
      - run:
          name: Check node version
          command: |
            node -v
            npm -v
      - run:
          name: Install node modules
          command: |
            npm i
      - run:
          name: Install python modules
          command: |
            pipenv sync
jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Unit Test
          command: |
            cd tests
            pipenv run pytest -v
            cd ../
      - run:
          name: Lint Test
          command: |
            pipenv run pylint src
  deploy-dev:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Deploy
          command: |
            ./node_modules/.bin/serverless deploy \
            --stage dev \
            --region ${AWS_DEFAULT_REGION}
  deploy-stg:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Deploy
          command: |
            ./node_modules/.bin/serverless deploy \
            --stage stg \
            --region ${AWS_DEFAULT_REGION}
  deploy-prod:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Deploy
          command: |
            ./node_modules/.bin/serverless deploy \
            --stage prod \
            --region ${AWS_DEFAULT_REGION}
  smoke-test:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Smoke test
          command: |
            ./node_modules/.bin/serverless invoke \
            -f ${FUNCTION_NAME} \
            -d "\{\}"
  rollback:
    executor:
      name: default
    steps:
      - checkout
      - setup
      - run:
          name: Get previous version
          command: |
            echo 'export TIMESTAMP=`sls deploy list --stage dev --region ap-northeast-1 | grep Datetime | tail -n 2 | sed -e "s/^Serverless: Datetime: //" | sed "2d"`' >> $BASH_ENV
      - run:
          name: Rollback
          command: |
            ./node_modules/.bin/serverless rollback \
            --stage dev \
            --region ${AWS_DEFAULT_REGION} \
            --timestamp ${TIMESTAMP}
workflows:
  version: 2.1
  deploy:
    jobs:
      - test
      - deploy-dev:
          context: aws-dev
          requires:
            - test
          filters:
            branches:
              only: /develop/
      - deploy-stg:
          context: aws-stg
          requires:
            - test
          filters:
            branches:
              only: /release/
      - deploy-prod:
          context: aws-prod
          requires:
            - test
          filters:
            branches:
              only: /master/
      - smoke-test:
          context: aws-prod
          requires:
            - deploy-prod
          filters:
            branches:
              only: /master/
