version: 2.1
executors:
  default:
    docker:
      - image: jiripuc/circleci-python-node:stretch-python-3.6.8-node-10.14.2
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
        name: install pipenv
        command: pip install pipenv
      - run:
        name: install serverless
        command: npm i serverless -g
      - run:
        name: pipenv install
        command: export PIPENV_VENV_IN_PROJECT=1 | pipenv sync
      - run:
        name: npm install
        command: npm ci
      - run:
        name: install serverless-dynamodb-local
        command: sls dynamodb install
      - run:
        name: activate pipenv
        command: pipenv shell
  lint:
    executor:
      name: default
    steps:
      - run:
        name: pylint
        command: pylint --rcfile=./settings/pylintrc src/*.py
  test:
    executor:
      name: default
    steps:
      - run:
        name: change directory
        command: cd tests
      - run:
        name: test
        command: pytest -v
  deploy:
    executor:
      name: default
    steps:
      - run:
        name: sls deploy
        command: sls deploy --stage dev --regiou us-east-1 --profile default
workflows:
  deploy-flow:
    jobs:
      - setup
      - lint:
        requires:
          - setup
      - test:
        requires:
          - lint
      - deploy:
        requires:
          - test

